[mypy]
python_version = 3.14
warn_unused_configs = True
ignore_missing_imports = True
follow_imports = silent
show_error_codes = True
pretty = True
exclude = (?x)(^tests/|^backup/|^data/)

[mypy-custom_components.ai_hub.*]
check_untyped_defs = True
disallow_incomplete_defs = False
disallow_untyped_defs = False
no_implicit_optional = True
