language: "zh-CN"
responses:
  intents:
    HassListAddItem:
      default: "已将{{ slots.item }}添加到{{ slots.name }}"
    HassListCompleteItem:
      default: "已完成{{ slots.name }}中的{{ slots.item }}"
    HassListRemoveItem:
      default: "已从{{ slots.name }}中删除{{ slots.item }}"