language: "zh-CN"

lists:
  climate_names:
    values:
      - "空调"
      - "冷气"
      - "暖气"
      - "地暖"
      - "加热器"
      - "取暖器"
      - "恒温器"
      - "温控器"
      - "新风"
      - "空气净化"
      - "加湿器"
      - "除湿器"

expansion_rules:
  temperature: "(温度|气温|室温)"

intents:
  HassClimateGetTemperature:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <what_is>{name}<temperature>"
          - "[<let>] <what_is><area><climate_names><temperature>"
          - "[<let>] <what_is>{area}<temperature>"
          - "<area>[的]<climate_names>[现在|当前]<what_is>多少度"
          - "<area>[的]<climate_names><temperature><like>"
          - "{name}<temperature><like>"
        requires_context:
          domain: climate
