language: "zh-CN"

lists:
  cover_states:
    values:
      - in: "(打开|开着|升起)"
        out: "open"
      - in: "(关闭|关着|关上|降下)"
        out: "closed"
      - in: "(正在打开|正在升起)"
        out: "opening"
      - in: "(正在关闭|正在降下)"
        out: "closing"
  cover_classes:
    values:
      - in: "(窗帘|帘子)"
        out: "curtain"
      - in: "百叶窗"
        out: "blind"
      - in: "卷帘"
        out: "roller"
      - in: "车库(门)"
        out: "garage"

intents:
  HassCoverGetState:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <function_verbs>[<area>](窗帘|百叶|遮阳帘){name}[的]状态"
          - "[<let>] [<area>](窗帘|百叶|遮阳帘){name}[是|不是]<action_verbs>[吗|不]"
        response: one_yesno
        requires_context:
          domain: cover
        slots:
          domain: cover
      - sentences:
          - "[<let>] [{area}][有|有没有]{cover_classes:device_class}[是|不是]{cover_states:state}[吗|不]"
        response: any
        slots:
          domain: cover
      - sentences:
          - "[<let>][<all>]{area_names}{cover_names}[都]是{cover_states:state}[吗|不]"
        response: all
        slots:
          domain: cover
      - sentences:
          - "[<let>][<which>][<area>]{cover_names}[是]{cover_states:state}"
        response: which
        slots:
          domain: cover
      - sentences:
          - "[<let>][<how_many_is>][<area>]{cover_names}[是]{cover_states:state}"
        response: how_many
        slots:
          domain: cover
