language: "zh-CN"

lists:
  message:
    values:
      - "消息"
      - "内容"
      - "信息"

intents:
  HassNotifyIntent:
    action: [notify]
    speech:
      text: 发送通知
    slots:
      message: { type: text }
    templates:
      - "[<let>] <function_verbs>通知<aux_words>{message}"
