language: "zh-CN"

local_intents:
  GlobalDeviceControl:
    off_keywords:
      - "关闭"
      - "关上"
      - "关"
      - "停止"
      - "熄灭"
      - "灭灯"
      - "关掉"
      - "暂停"
      - "退出"
    responses:
      success_off: "已关闭{count}个设备{fail_msg}"

intents:
  HassTurnOff:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <turn_off>[<area>]{name}"
          - "[<let>] [把][<area>]{name}<turn_off>"
          - "[<let>] <turn_off>{area_names}<all>{light_names}"
          - "[<let>] [把]{area_names}<all>{light_names}<turn_off>"
        slots:
          domain: all
