language: "zh-CN"
intents:
  HassTurnOff:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <turn_off>[<area>]{name}"
          - "[<let>] [把][<area>]{name}[关闭|关掉|关上]"
          - "[<let>] <turn_off>{area_names}[所有|所有的|全部|全部的]{light_names}"
          - "[<let>] [把]{area_names}[所有|所有的|全部|全部的]{light_names}[关闭|关掉|关上]"
        slots:
          domain: all