language: "zh-CN"
intents:
  HassTurnOn:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <turn_on>[<area>]<lock_names>"
          - "[<let>] [把][<area>]<lock_names><turn_on>"
        requires_context:
          domain: lock
