language: "zh-CN"
intents:
  HassTurnOff:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <turn_off>[<area>]<lock_names>"
          - "[<let>] [把][<area>]<lock_names>[关闭|锁上|上锁]"
        requires_context:
          domain: lock