language: "zh-CN"
intents:
  HassTurnOff:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <turn_off>[<area>]<lock_names>"
          - "[<let>] [把][<area>]<lock_names><turn_off>"
        requires_context:
          domain: lock
