language: "zh-CN"

lists:
  lock_names:
    values:
      - "门锁"
      - "智能锁"
      - "电子锁"
      - "密码锁"
      - "指纹锁"
      - "人脸识别锁"
      - "门禁"
      - "自动门"
      - "防盗门"
  lock_states:
    values:
      - in: "(锁上|锁着|已锁)"
        out: "locked"
      - in: "(没锁|未锁|开着|打开)"
        out: "unlocked"

local_intents:
  GlobalDeviceControl:
    domain_services:
      lock:
        turn_on: "unlock"
        turn_off: "lock"
        open: "open"
    default_device_names:
      lock: "门锁"

intents:
  HassGetState:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <function_verbs>[<area>]{name}[的锁](是不是|有没有){lock_states:state}"
          - "[<let>] [<area>]{name}[的锁][是|有]{lock_states:state}[吗|不]"
        response: one_yesno
        requires_context:
          domain: lock
        slots:
          domain: lock
