language: "zh-CN"
intents:
  HassMediaMute:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <turn_off>{name}"
          - "[<let>] <turn_off>[声音]{name}"
          - "[<let>] {name}<turn_off>"
        requires_context:
          domain: "media_player"
