language: "zh-CN"
intents:
  HassSetVolume:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <set><area>[的]<media_player_names>[音量]<volume_percentage>"
          - "[<let>] <set><name>[音量]<volume_percentage>"
          - "[<let>] <set>[音量]<volume_percentage>"
        requires_context:
          domain: media_player