language: "zh-CN"

local_intents:
  GlobalDeviceControl:
    responses:
      success_scene: "已激活场景：{scene_name}"

intents:
  HassActivateScene:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <turn_on>{name}[场景]"
          - "[<let>] <turn_on>{name}[场景]"
          - "[<let>] <turn_on>{name}[场景]"
        requires_context:
          domain: "scene"
