language: "zh-CN"

lists:
  sensor_names:
    values:
      - "传感器"
      - "温度传感器"
      - "湿度传感器"
      - "温湿度传感器"
      - "光照传感器"
      - "人体传感器"
      - "运动传感器"
      - "人体感应器"
      - "门窗传感器"
      - "烟雾报警器"
      - "燃气报警器"
      - "水浸传感器"
      - "空气质量"
      - "甲醛检测"
  bs_battery_states:
    values:
      - in: "(低电量|没电)"
        out: "on"
      - in: "(充满电|满电)"
        out: "off"

intents:
  HassGetState:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <function_verbs>[<area>]{name}[的]<state>"
          - "[<let>] [<area>]{name}<state><like>"
          - "[<let>] [<area>]{name}[现在|当前]<what_is>"
          - "[<let>] <function_verbs>[<area>]{name}[有没有|是不是]{bs_battery_states:state}"
        response: one_yesno
        requires_context:
          domain: sensor
        slots:
          domain: sensor
