language: "zh-CN"
intents:
  HassShoppingListCompleteItem:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] [完成]{item}"
          - "[<let>] {item}[已买]"
          - "[<let>] [标记]{item}[完成]"