language: "zh-CN"

lists:
  todo_list_item:
    values:
      - "待办"
      - "任务"
      - "事项"

intents:
  HassListAddItem:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <add><item><add_to>{name}"
          - "[<let>] <add>{name}<add_to><item>"
          - "[<let>] <add><item>[到]{name}"
        slots:
          item:
            type: text
          name:
            type: text
