language: "zh-CN"
intents:
  HassValveOpen:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <turn_on>{name}"
          - "[<let>] {name}<turn_on>"
        requires_context:
          domain: "valve"
