language: "zh-CN"
intents:
  HassValveClose:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <turn_off>{name}"
          - "[<let>] {name}<turn_off>"
        requires_context:
          domain: "valve"
