language: "zh-CN"
intents:
  HassValveOpen:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] [打开]{name}"
          - "[<let>] {name}[打开]"
        requires_context:
          domain: "valve"