language: "zh-CN"

lists:
  on_off_states:
    values:
      - in: "开(着|启)"
        out: "on"
      - in: "关(着|闭)"
        out: "off"

intents:
  HassGetWeather:
    use_home_assistant: true
    data:
      - sentences:
          - "[<let>] <what_is><area><weather>"
          - "[<let>] <what_is><weather>"
          - "<area><weather><like>"
          - "<area><weather>怎么样"
          - "今天天气[怎么样|如何]"
